name: WR802N-v1 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: config-repo

    - name: Cache OpenWrt
      uses: actions/cache@v3
      with:
        path: |
          openwrt-src/dl
          openwrt-src/build_dir
          ~/.ccache
        key: ${{ runner.os }}-openwrt-${{ hashFiles('config-repo/.config') }}

    - name: Clone OpenWrt
      run: |
        git clone --depth=1 --branch v22.03.5 https://github.com/openwrt/openwrt.git openwrt-src

    - name: Install Dependencies
      uses: arduino/setup-task@v1
      with:
        taskfile: ci/Taskfile.yml

    - name: Setup Python
      run: |
        python3 -m venv ~/venv
        source ~/venv/bin/activate

    - name: Apply Patches
      run: |
        cd openwrt-src
        # 使用更规范的补丁方式
        quilt new wr802n_mod.patch
        quilt edit target/linux/ath79/dts/qca9533_tplink_tl-wr802n-v1.dts
        sed -i 's/reg = <0x50000 0x7b0000>/reg = <0x50000 0x3c00000>/' \
          target/linux/ath79/dts/qca9533_tplink_tl-wr802n-v1.dts
        quilt refresh

        cp -r ../config-repo/files files
        find files/etc/config -type d -exec chmod 0755 {} \;
        find files/etc/config -type f -exec chmod 0644 {} \;
        cp ../config-repo/.config .

    - name: Build Firmware
      run: |
        set -euxo pipefail
        cd openwrt-src
        source ~/venv/bin/activate
        
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        make defconfig
        sed -i 's/CONFIG_INITRAMFS_COMPRESSION_LZ4=y/# CONFIG_INITRAMFS_COMPRESSION_LZ4 is not set/' .config
        sed -i 's/CONFIG_RD_LZ4=y/# CONFIG_RD_LZ4 is not set/' .config
        sed -i 's/CONFIG_INITRAMFS_COMPRESSION_ZSTD=y/# CONFIG_INITRAMFS_COMPRESSION_ZSTD is not set/' .config
        sed -i 's/CONFIG_RD_ZSTD=y/# CONFIG_RD_ZSTD is not set/' .config
        
        make -j$(($(nproc) + 2)) V=s || (make V=s -j1; exit 1)

    - name: Verify firmware
      run: |
        cd openwrt-src/bin/targets/ath79/generic/
        FIRMWARE=$(ls openwrt-ath79-*.bin)
        strings $FIRMWARE | grep -q 'qca9533' || (echo "芯片验证失败"; exit 1)
        grep -aq '172.18.18.1' $FIRMWARE || (echo "IP配置丢失"; exit 1)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: openwrt-src/bin/targets/ath79/generic/openwrt-ath79-*.bin
