name: WR802N-v1 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: config-repo

    - name: Cache OpenWrt
      uses: actions/cache@v3
      with:
        path: |
          openwrt-src/dl
          openwrt-src/build_dir
          ~/.ccache
        key: ${{ runner.os }}-openwrt-${{ hashFiles('config-repo/.config') }}

    - name: Clone OpenWrt
      run: |
        git clone --depth=1 --branch v22.03.5 https://github.com/openwrt/openwrt.git openwrt-src

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget \
          python3 python3-venv

    - name: Setup Python
      run: |
        python3 -m venv ~/venv
        source ~/venv/bin/activate

    - name: Apply Patches
      run: |
        cd openwrt-src
        mkdir -p package/ath79/patches
        ls
        
        # 生成标准补丁文件
        cat << 'EOF' > package/ath79/patches/100-wr802n-memory.patch
        --- a/target/linux/ath79/dts/qca9533_tplink_tl-wr802n-v1.dts
        +++ b/target/linux/ath79/dts/qca9533_tplink_tl-wr802n-v1.dts
        @@ -30,7 +30,7 @@
                 partitions {
                         compatible = "fixed-partitions";
                         #address-cells = <1>;
                         #size-cells = <1>;
        -                reg = <0x50000 0x7b0000>;
        +                reg = <0x50000 0x3c00000>;
 
                         partition@0 {
                                 label = "u-boot";
        EOF
        
        # 更新并应用补丁
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        # 复制配置文件
        cp -r ../config-repo/files files
        find files/etc/config -type d -exec chmod 0755 {} \;
        find files/etc/config -type f -exec chmod 0644 {} \;
        cp ../config-repo/.config .

    - name: Apply Config
      run: |
        cd openwrt-src
        # 使用完整配置覆盖
        cp ../config-repo/.config .
        sed -i 's/reg = <0x50000 0x7b0000>/reg = <0x50000 0x3c00000>/' \
          target/linux/ath79/dts/qca9533_tplink_tl-wr802n-v1.dts
        ls
        
        # 必须禁用自动配置
        touch .config
        make defconfig
        ./scripts/diffconfig.sh > diffconfig
        if ! grep -q 'CONFIG_TARGET_ath79_generic_DEVICE_tplink_tl-wr802n-v1=y' diffconfig; then
          echo "设备配置丢失，当前配置："
          cat diffconfig
          exit 1
        fi

    - name: Build Firmware
      run: |
        set -euxo pipefail
        cd openwrt-src
        source ~/venv/bin/activate
        
        make defconfig
        sed -i 's/CONFIG_INITRAMFS_COMPRESSION_LZ4=y/# CONFIG_INITRAMFS_COMPRESSION_LZ4 is not set/' .config
        sed -i 's/CONFIG_RD_LZ4=y/# CONFIG_RD_LZ4 is not set/' .config
        sed -i 's/CONFIG_INITRAMFS_COMPRESSION_ZSTD=y/# CONFIG_INITRAMFS_COMPRESSION_ZSTD is not set/' .config
        sed -i 's/CONFIG_RD_ZSTD=y/# CONFIG_RD_ZSTD is not set/' .config
        
        make V=s -j1


    - name: Verify Firmware
      run: |
        cd openwrt-src/bin/targets/ath79/generic/
        echo "=== 强制检查WR802N固件 ==="
        if ! ls openwrt-ath79-generic-tplink_tl-wr802n-v1-*.bin 2>/dev/null; then
          echo "找到以下固件:"
          ls -lh *.bin
          echo "错误：未生成目标设备固件"
          exit 1
        fi
        
        FIRMWARE=$(ls openwrt-ath79-generic-tplink_tl-wr802n-v1-*.bin)
        strings $FIRMWARE | grep -q 'qca9533' || (echo "芯片验证失败（最后检查）"; exit 1)

        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: openwrt-src/bin/targets/ath79/generic/openwrt-ath79-*.bin
