name: WR802N-v1 Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: config-repo

    - name: Clone OpenWrt
      run: |
        git clone --depth=1 https://github.com/openwrt/openwrt.git -b v22.03.5 openwrt-src

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget \
          python3 python3-venv
        python3 -m venv ~/venv
        source ~/venv/bin/activate

    - name: Apply patches
      run: |
        cd openwrt-src
        # 修改设备树
        sed -i 's/reg = <0x50000 0x7b0000>/reg = <0x50000 0x3c00000>/' \
          target/linux/ath79/dts/qca9533_tplink_tl-wr802n-v1.dts
        
        # 部署配置文件
        cp -r ../config-repo/files files
        cp ../config-repo/.config .

    - name: Build firmware
      run: |
        cd openwrt-src
        source ~/venv/bin/activate
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make -j$(($(nproc) + 2)) V=s

    - name: Verify firmware
      run: |
        cd openwrt-src/bin/targets/ath79/generic/
        FIRMWARE=$(ls openwrt-*-tplink_tl-wr802n-v1-*.bin)
        strings $FIRMWARE | grep -q 'qca9533' || (echo "芯片验证失败"; exit 1)
        grep -aq '172.18.18.1' $FIRMWARE || (echo "IP配置丢失"; exit 1)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: openwrt-src/bin/targets/ath79/generic/openwrt-*-tplink_tl-wr802n-v1-*.bin
