name: WR802N-v1 Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: config-repo

    - name: Clone OpenWrt 
      run: |
        git clone --depth=1 https://github.com/openwrt/openwrt.git -b v22.03.5 openwrt-src

    - name: 设置环境
      run: |
        cd openwrt-src
        # 修正设备树配置
        sed -i 's/reg = <0x50000 0x7b0000>/reg = <0x50000 0x3c00000>/' \
          target/linux/ath79/dts/qca9533_tplink_tl-wr802n-v1.dts
        # 复制配置文件并修复权限
        cp -r ../config-repo/files files
        find files/etc/config -type d -exec chmod 0755 {} \;  # 目录权限
        find files/etc/config -type f -exec chmod 0644 {} \;  # 文件权限
        sudo chown -R root:root files/etc/config                   # 所有者
        cp ../config-repo/.config .

    - name: 应用补丁和修复权限
      run: |
        cd openwrt-src
        # 修改设备树
        sed -i 's/reg = <0x50000 0x7b0000>/reg = <0x50000 0x3c00000>/' \
          target/linux/ath79/dts/qca9533_tplink_tl-wr802n-v1.dts
        
        # 部署配置文件
        cp -r ../config-repo/files files
        cp ../config-repo/.config .

    - name: 构建固件
      run: |
        cd openwrt-src
        source ~/venv/bin/activate
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        # 确保清理旧配置（可选）
        make clean
        make defconfig
        # 强制禁用 LZ4/ZSTD（从日志中提取）
        sed -i 's/CONFIG_INITRAMFS_COMPRESSION_LZ4=y/# CONFIG_INITRAMFS_COMPRESSION_LZ4 is not set/' .config
        sed -i 's/CONFIG_RD_LZ4=y/# CONFIG_RD_LZ4 is not set/' .config
        sed -i 's/CONFIG_INITRAMFS_COMPRESSION_ZSTD=y/# CONFIG_INITRAMFS_COMPRESSION_ZSTD is not set/' .config
        sed -i 's/CONFIG_RD_ZSTD=y/# CONFIG_RD_ZSTD is not set/' .config
        make -j$(($(nproc) + 2)) V=s

    - name: Verify firmware
      run: |
        cd openwrt-src/bin/targets/ath79/generic/
        FIRMWARE=$(ls openwrt-*-tplink_tl-wr802n-v1-*.bin)
        strings $FIRMWARE | grep -q 'qca9533' || (echo "芯片验证失败"; exit 1)
        grep -aq '172.18.18.1' $FIRMWARE || (echo "IP配置丢失"; exit 1)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: openwrt-src/bin/targets/ath79/generic/openwrt-*-tplink_tl-wr802n-v1-*.bin
