name: WR802N-v1 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: config-repo

    - name: Cache OpenWrt
      uses: actions/cache@v3
      id: openwrt-cache
      with:
        path: |  # 缓存路径
          openwrt/dl       # 下载目录
          openwrt/build_dir # 构建目录
          ~/.ccache            # 编译缓存
        key: ${{ runner.os }}-openwrt-${{ hashFiles('openwrt/scripts/feeds') }}
        restore-keys: |  # 缓存回退机制
          ${{ runner.os }}-openwrt-

    - name: Clone OpenWrt
      run: |
        git clone https://github.com/openwrt/openwrt.git

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget \
          python3 python3-venv

    - name: Setup Python
      run: |
        python3 -m venv ~/venv
        source ~/venv/bin/activate

    - name: Apply Patches
      run: |
        cd openwrt
        sed -i '343s/4mlzma/16mlzma/g' target/linux/ath79/image/tiny-tp-link.mk
        cat target/linux/ath79/image/tiny-tp-link.mk
        
        sed -i '70s/0x3d0000/0xfd0000/g' target/linux/ath79/dts/qca9533_tplink_tl-wr802n.dtsi
        sed -i '76s/0x3f0000/0xff0000/g' target/linux/ath79/dts/qca9533_tplink_tl-wr802n.dtsi
        cat target/linux/ath79/dts/qca9533_tplink_tl-wr802n.dtsi
        
        
        # 更新并应用补丁
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        # 复制配置文件
        cp -r ../config-repo/files files
        find files/etc/config -type d -exec chmod 0755 {} \;
        find files/etc/config -type f -exec chmod 0644 {} \;
        cp ../config-repo/.config .

    - name: Build Firmware
      run: |
        set -euxo pipefail
        cd openwrt
        source ~/venv/bin/activate
        
        make defconfig
        sed -i 's/CONFIG_INITRAMFS_COMPRESSION_LZ4=y/# CONFIG_INITRAMFS_COMPRESSION_LZ4 is not set/' .config
        sed -i 's/CONFIG_RD_LZ4=y/# CONFIG_RD_LZ4 is not set/' .config
        sed -i 's/CONFIG_INITRAMFS_COMPRESSION_ZSTD=y/# CONFIG_INITRAMFS_COMPRESSION_ZSTD is not set/' .config
        sed -i 's/CONFIG_RD_ZSTD=y/# CONFIG_RD_ZSTD is not set/' .config
        
        make V=s -j1


#    - name: Verify Firmware
#      run: |
#        cd openwrt/bin/targets/ath79/tiny/
#        echo "=== 固件列表 ==="
#        ls -lh *.bin
#        echo "=== 固件信息验证 ==="
#        FIRMWARE="openwrt-ath79-tiny-tplink_tl-wr802n-v1-squashfs-sysupgrade.bin"
#        strings $FIRMWARE | grep -m1 'qca9533' || (echo "芯片验证失败（二进制检查）"; exit 1)
#        strings $FIRMWARE | grep -q '172.18.18.1' || (echo "IP配置丢失"; exit 1)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: openwrt/bin/targets/ath79/tiny/openwrt-ath79-*.bin
