name: WR802N-v1 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: config-repo

    - name: Cache OpenWrt
      uses: actions/cache@v3
      with:
        path: |
          openwrt-src/dl
          openwrt-src/build_dir
          ~/.ccache
        key: ${{ runner.os }}-openwrt-${{ hashFiles('config-repo/.config') }}

    - name: Clone OpenWrt
      run: |
        git clone --depth=1 --branch v22.03.5 https://github.com/openwrt/openwrt.git openwrt-src

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget \
          python3 python3-venv

    - name: Setup Python
      run: |
        python3 -m venv ~/venv
        source ~/venv/bin/activate

    - name: Apply Patches
      run: |
        cd openwrt-src
        mkdir -p target/linux/ath79/patches-5.10
        
        # 生成标准补丁文件
        cat << 'EOF' > target/linux/ath79/patches-5.10/100-wr802n-memory.patch
        --- a/target/linux/ath79/dts/qca9533_tplink_tl-wr802n-v1.dts
        +++ b/target/linux/ath79/dts/qca9533_tplink_tl-wr802n-v1.dts
        @@ -30,7 +30,7 @@
                 partitions {
                         compatible = "fixed-partitions";
                         #address-cells = <1>;
                         #size-cells = <1>;
        -                reg = <0x50000 0x7b0000>;
        +                reg = <0x50000 0x3c00000>;
 
                         partition@0 {
                                 label = "u-boot";
        EOF
        
        # 复制配置文件
        cp -r ../config-repo/files files
        find files/etc/config -type d -exec chmod 0755 {} \;
        find files/etc/config -type f -exec chmod 0644 {} \;
        cp ../config-repo/.config .

    - name: Apply Config
      run: |
        cd openwrt-src
        make oldconfig
        ./scripts/diffconfig.sh > diffconfig
        if ! grep -q 'CONFIG_TARGET_ath79_generic_DEVICE_tplink_tl-wr802n-v1=y' diffconfig; then
          echo "设备配置丢失，当前配置："
          cat diffconfig
          exit 1
        fi

    - name: Build Firmware
      run: |
        set -euxo pipefail
        cd openwrt-src
        source ~/venv/bin/activate
        
        make PROFILE="tplink_tl-wr802n-v1" \
            -j$(($(nproc) + 2)) V=s || (make V=s -j1; exit 1)

    - name: Verify Firmware
      run: |
        cd openwrt-src/bin/targets/ath79/generic/
        echo "=== 固件详情 ==="
        FIRMWARE=$(ls openwrt-ath79-generic-tplink_tl-wr802n-v1-*.bin)
        file $FIRMWARE
        strings $FIRMWARE | grep -q 'qca9533' || (echo "芯片验证失败"; exit 1)
        grep -aq '172.18.18.1' $FIRMWARE || (echo "IP配置丢失"; exit 1)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: openwrt-src/bin/targets/ath79/generic/openwrt-ath79-generic-tplink_tl-wr802n-v1-*.bin
