name: WR802N-v1 Custom Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout project repo
      uses: actions/checkout@v4
      with:
        path: config-repo

    - name: Clone OpenWrt source
      run: |
        git clone --depth=1 https://git.openwrt.org/openwrt/openwrt.git -b v22.03.5 openwrt-src
        echo "OpenWrt version: $(cat openwrt-src/version)"

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget python3-venv

        # 创建Python虚拟环境
        python3 -m venv ~/openwrt-env
        source ~/openwrt-env/bin/activate
        pip install wheel

    - name: Apply hardware patches
      run: |
        # 进入源码目录
        cd openwrt-src

        # 确认设备树文件存在
        DTS_PATH="target/linux/ath79/dts/qca9533_tplink_tl-wr802n-v1.dts"
        if [ ! -f "$DTS_PATH" ]; then
          echo "错误：设备树文件未找到！"
          find . -name '*wr802n*.dts'
          exit 1
        fi

        # 修改Flash分区 (适配64MB)
        sed -i 's/reg = <0x50000 0x7b0000>/reg = <0x50000 0x3c00000>/' "$DTS_PATH"

        # 配置无线热点
        mkdir -p files/etc/config
        cat > files/etc/config/wireless << EOF
        config wifi-device 'radio0'
            option type 'mac80211'
            option channel '6'
            option hwmode '11g'
            option path 'pci0000:00/0000:00:00.0'
            option txpower '20'
            option country 'CN'
        
        config wifi-iface
            option device 'radio0'
            option network 'lan'
            option mode 'ap'
            option ssid 'WR802N-v1-AP'
            option encryption 'psk2'
            option key 'yourpassword'
        EOF

        # 配置LAN IP地址
        cat > files/etc/config/network << EOF
        config interface 'loopback'
            option ifname 'lo'
            option proto 'static'
            option ipaddr '127.0.0.1'
            option netmask '255.0.0.0'
        
        config interface 'lan'
            option ifname 'eth0'
            option proto 'static'
            option ipaddr '172.18.18.1'
            option netmask '255.255.255.0'
        EOF

        # 复制主配置文件
        cp ../config-repo/.config .

    - name: Initialize feeds
      run: |
        cd openwrt-src
        source ~/openwrt-env/bin/activate
        # echo 'src-git tailscale https://github.com/tailscale/openwrt-tailscale.git' >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build firmware
      run: |
        cd openwrt-src
        source ~/openwrt-env/bin/activate
        make defconfig
        make -j$(($(nproc) + 1)) V=s

    - name: Verify firmware
      run: |
        cd openwrt-src/bin/targets/ath79/generic/
        if ! strings openwrt-*-tl-wr802n-v1-*.bin | grep -q 'qca9533'; then
          echo "固件芯片验证失败！"
          exit 1
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wr802n-v1-firmware
        path: openwrt-src/bin/targets/ath79/generic/openwrt-*-tl-wr802n-v1-squashfs-sysupgrade.bin

    - name: Cleanup
      if: always()
      run: |
        sudo swapoff /swapfile || true
        sudo rm -f /swapfile || true
