name: WR802N-v1 Custom Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout project repo
      uses: actions/checkout@v4

    - name: Clone OpenWrt source
      run: |
        git clone --depth=1 https://git.openwrt.org/openwrt/openwrt.git -b v22.03.5 openwrt-src

    - name: Install dependencies (Python 3 fix)
      run: |
        sudo apt-get update
        # 修复关键依赖
        sudo apt-get install -y \
          python3 \
          python3-pip \
          python3-setuptools \
          python3-dev \
          build-essential \
          clang \
          flex \
          bison \
          g++ \
          gawk \
          gcc-multilib \
          g++-multilib \
          gettext \
          git \
          libncurses-dev \
          libssl-dev \
          rsync \
          unzip \
          zlib1g-dev \
          file \
          wget

        # 确保 distutils 可用
        python3 -m ensurepip --upgrade
        pip3 install --user setuptools

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Create swap space
      run: |
        sudo fallocate -l 8G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        free -h

    - name: Apply hardware patches
      run: |
        # 复制主配置
        cp config-repo/wr802n.config openwrt-src/

        # 修改v1设备树（适配64MB Flash）
        sed -i 's/<0x50000 0x7a0000>/<0x50000 0x3c00000>/' \
          openwrt-src/target/linux/ar71xx/dts/ar9331_tl-wr802n-v1.dts

        # 配置无线热点
        mkdir -p openwrt-src/files/etc/config
        cat > openwrt-src/files/etc/config/wireless << EOF
        config wifi-device 'radio0'
            option type 'mac80211'
            option channel '6'
            option hwmode '11g'
            option path 'platform/ar933x_wmac'
            option txpower '20'
            option country 'CN'

        config wifi-iface
            option device 'radio0'
            option network 'lan'
            option mode 'ap'
            option ssid 'OpenWrt-v1'
            option encryption 'psk2'
            option key '12345678'
        EOF

        # 配置LAN IP
        cat > openwrt-src/files/etc/config/network << EOF
        config interface 'loopback'
            option ifname 'lo'
            option proto 'static'
            option ipaddr '127.0.0.1'
            option netmask '255.0.0.0'

        config interface 'lan'
            option ifname 'eth0'
            option proto 'static'
            option ipaddr '172.18.18.1'
            option netmask '255.255.255.0'
        EOF

    - name: Initialize feeds
      run: |
        cd openwrt-src
        echo 'src-git tailscale https://github.com/tailscale/openwrt-tailscale.git' >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a -p tailscale

    - name: Build firmware
      run: |
        cd openwrt-src
        make defconfig
        make -j$(($(nproc) + 1)) V=s

    - name: Verify firmware
      run: |
        cd openwrt-src/bin/targets/ar71xx/generic/
        if ! grep -q 'ar9331_tl-wr802n-v1' *.bin; then
          echo "固件设备验证失败！"
          exit 1
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # 关键修复点
      with:
        name: wr802n-v1-firmware
        path: openwrt-src/bin/targets/ar71xx/generic/openwrt-*-tl-wr802n-v1-squashfs-sysupgrade.bin
        compression-level: 0  # 新增推荐参数
        overwrite: true

    - name: Cleanup
      if: always()
      run: |
        sudo swapoff /swapfile
        sudo rm -f /swapfile
